project:
  type: book

book:
  title: "Statistical Reasoning"
  author: 
    - "Wouter de Nooy"
    - "Sharon Klinkenberg"
  date: "7/14/2023"
  chapters:
    - index.qmd
    - 01-samplingdistr.qmd
    - 02-probability.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    toc-depth: 2
    toc-location: right
    number-depth: 2
  # pdf:
  #   documentclass: scrreprt



